<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-27 at 18:15:17.
 */
class AfficheTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Affiche
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Affiche;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Affiche::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue() {
        $this->assertNull('mon test');
    }

    /**
     * @covers Affiche::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        $this->assertEquals("mon test");
    }

}
