<?php
$temp = explode("/",$_SERVER['SCRIPT_FILENAME']);
$folder = "";
if(count($temp)<=1){
    $temp = explode("\\",$_SERVER['SCRIPT_FILENAME']);
    for($i=0;$i<count($temp)-3;$i++){
        $folder .= $temp[$i]."\\";
    }
    $file = "src\\affiche.php";
} else {
    for($i=0;$i<count($temp)-3;$i++){
        $folder .= $temp[$i]."/";
    }
    $file = "src/affiche.php";
}
require_once $folder.$file;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-27 at 18:15:17.
 */
class AfficheTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Affiche
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Affiche;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Affiche::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue() {
        $this->assertNull($this->object->setValue('mon test'));
    }

    /**
     * @covers Affiche::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        $this->assertEquals("mon test",$this->object->getValue());
    }

    /**
     * @covers Affiche::setValue2
     * @todo   Implement testSetValue2().
     */
    public function testSetValue2() {
        $this->assertNull($this->object->setValue2('mon test 2'));
    }

    /**
     * @covers Affiche::getValue2
     * @todo   Implement testGetValue2().
     */
    public function testGetValue2() {
        $this->assertEquals("mon test 2",$this->object->getValue2());
    }

}
